create index if not exists idx_users_line_uid on public.users(line_uid);
create index if not exists idx_jobs_published_created_at on public.jobs(is_published, created_at desc);
create index if not exists idx_jobs_organization_id on public.jobs(organization_id);
create index if not exists idx_bookmarks_user_created_at on public.bookmarks(user_id, created_at desc);
create index if not exists idx_bookmarks_job_id on public.bookmarks(job_id);
create index if not exists idx_articles_section_published_at on public.articles(section, is_published, published_at desc);
create index if not exists idx_classes_day_period on public.classes(day_of_week, period);
create index if not exists idx_class_assignments_class_due_at on public.class_assignments(class_id, due_at);
create index if not exists idx_class_assignment_completions_user_id on public.class_assignment_completions(user_id);
create index if not exists idx_class_user_settings_user_id on public.class_user_settings(user_id);
