name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Workload Identity 連携で必要なパーミッション設定
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔑 ここで先ほど設定したシークレットを使ってGoogle Cloudにログインします
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      # (例) ログインに成功したか、Gcloud CLIのテストを実行
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
